### ISSUE TITLE
Problem connecting to TV

### ISSUE THREAD

**Issue by blinciki-lol** [KyroFrCode/moonlight-chrome-tizen-docker#1]
Hello,

I have tried to set it up together with a friend, but got stuck at the sdb connect TV_IP step.

I enabled developer mode on my TV and gave it the IP address of docker container. I also built the application and ran docker and when trying to connect to the TV: sdb connect TV_IP, the result was always a failed connection.

Output:
connecting to TV_IP
failed to connect to TV_IP

Could you help with this step or do you have any clues how to debug the problem?

**Comment by RS-dev7** [comment]
I had a similar problem. You have to give the TV your host IP. I also launched it with `docker run -it --rm moonlight-tizen -p 80:80` rather than just `docker run -it --rm moonlight-tizen` but I don't know if that contributed to the fix. Mainly just have to give the TV the host IP.

**Comment by blinciki-lol** [comment]
Thank you, this solved the problem, the solution is to use the host IP address. 
(I have another problem now, but I'll open a new issue)
