### ISSUE TITLE
I have an issue

### ISSUE THREAD

**Issue by lion9994** [KyroFrCode/moonlight-chrome-tizen-docker#15]
=> ERROR [base 19/25] RUN cmake  -DCMAKE_TOOLCHAIN_FILE=/home/moonlight/emscripten-release-bundle/emsdk/fastcomp  0.3s
------
 > [base 19/25] RUN cmake       -DCMAKE_TOOLCHAIN_FILE=/home/moonlight/emscripten-release-bundle/emsdk/fastcomp/emscripten/cmake/Modules/Platform/Emscripten.cmake      -G Ninja        -S moonlight-chrome-tizen       -B build:
0.255 CMake Error: The source directory "/home/moonlight/moonlight-chrome-tizen" does not appear to contain CMakeLists.txt.
0.255 Specify --help for usage, or press the help button on the CMake GUI.

**Comment by leodoi3** [comment]
Having the same problem. How did you fix it?

**Comment by zerlas** [comment]
Found the solution in open issues,
Use the other up to date repo
https://github.com/KyroFrCode/moonlight-chrome-tizen
